//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWindDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWindDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryId	CategoryName	Description	Picture
        ///1	Beverages	Soft drinks, coffees, teas, beers, and ales	0x151C2F00020000000D000E0014002100FFFFFFFF4269746D617020496D616765005061696E742E5069637475726500010500000200000007000000504272757368000000000000000000A0290000424D98290000000000005600000028000000AC00000078000000010004000000000000000000880B0000880B00000800000008000000FFFFFF0000FFFF00FF00FF000000FF00FFFF000000FF0000FF00000000000000000010000000001000000001001000000000000001010100010000100100000001010001000000100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerId	CompanyName	ContactName	ContactTitle	Address	City	Region	PostalCode	Country	Phone	Fax
        ///ALFKI	Alfreds Futterkiste	Maria Anders	Sales Representative	Obere Str. 57	Berlin	NULL	12209	Germany	030-0074321	030-0076545
        ///ANATR	Ana Trujillo Emparedados y helados	Ana Trujillo	Owner	Avda. de la Constitución 2222	México D.F.	NULL	05021	Mexico	(5) 555-4729	(5) 555-3745
        ///ANTON	Antonio Moreno Taquería	Antonio Moreno	Owner	Mataderos  2312	México D.F.	NULL	05023	Mexico	(5) 555-3932	NULL
        ///AROUT	Around the Horn	Thom [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId	LastName	FirstName	Title	TitleOfCourtesy	BirthDate	HireDate	Address	City	Region	PostalCode	Country	HomePhone	Extension	Photo	Notes	ReportsTo	PhotoPath
        ///1	Davolio	Nancy	Sales Representative	Ms.	1948-12-08 00:00:00.000	1992-05-01 00:00:00.000	507 - 20th Ave. E. Apt. 2A	Seattle	WA	98122	USA	(206) 555-9857	5467	0x151C2F00020000000D000E0014002100FFFFFFFF4269746D617020496D616765005061696E742E506963747572650001050000020000000700000050427275736800000000000000000020540000424D205400000000000076000000280000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId	TerritoryId
        ///1	06897
        ///1	19713
        ///2	01581
        ///2	01730
        ///2	01833
        ///2	02116
        ///2	02139
        ///2	02184
        ///2	40222
        ///3	30346
        ///3	31406
        ///3	32859
        ///3	33607
        ///4	20852
        ///4	27403
        ///4	27511
        ///5	02903
        ///5	07960
        ///5	08837
        ///5	10019
        ///5	10038
        ///5	11747
        ///5	14450
        ///6	85014
        ///6	85251
        ///6	98004
        ///6	98052
        ///6	98104
        ///7	60179
        ///7	60601
        ///7	80202
        ///7	80909
        ///7	90405
        ///7	94025
        ///7	94105
        ///7	95008
        ///7	95054
        ///7	95060
        ///8	19428
        ///8	44122
        ///8	45839
        ///8	53404
        ///9	03049
        ///9	03801
        ///9	48075
        ///9	48084
        ///9	48304
        ///9	55113
        ///9	55439.
        /// </summary>
        public static string EmployeeTerritories {
            get {
                return ResourceManager.GetString("EmployeeTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderId	ProductId	UnitPrice	Quantity	Discount
        ///10248	11	14.00	12	0
        ///10248	42	9.80	10	0
        ///10248	72	34.80	5	0
        ///10249	14	18.60	9	0
        ///10249	51	42.40	40	0
        ///10250	41	7.70	10	0
        ///10250	51	42.40	35	0.15
        ///10250	65	16.80	15	0.15
        ///10251	22	16.80	6	0.05
        ///10251	57	15.60	15	0.05
        ///10251	65	16.80	20	0
        ///10252	20	64.80	40	0.05
        ///10252	33	2.00	25	0.05
        ///10252	60	27.20	40	0
        ///10253	31	10.00	20	0
        ///10253	39	14.40	42	0
        ///10253	49	16.00	40	0
        ///10254	24	3.60	15	0.15
        ///10254	55	19.20	21	0.15
        ///10254	74	8.00	21	0
        ///10255	2	15.20	20	0
        ///10255	16	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderId	CustomerId	EmployeeId	OrderDate	RequiredDate	ShippedDate	ShipVia	Freight	ShipName	ShipAddress	ShipCity	ShipRegion	ShipPostalCode	ShipCountry
        ///10248	VINET	5	1996-07-04 00:00:00.000	1996-08-01 00:00:00.000	1996-07-16 00:00:00.000	3	32.38	Vins et alcools Chevalier	59 rue de l&apos;Abbaye	Reims	NULL	51100	France
        ///10249	TOMSP	6	1996-07-05 00:00:00.000	1996-08-16 00:00:00.000	1996-07-10 00:00:00.000	1	11.61	Toms Spezialitäten	Luisenstr. 48	Münster	NULL	44087	Germany
        ///10250	HANAR	4	1996-07-08 00:00:00.000	1996- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId	ProductName	SupplierId	CategoryId	QuantityPerUnit	UnitPrice	UnitsInStock	UnitsOnOrder	ReorderLevel	Discontinued
        ///1	Chai	1	1	10 boxes x 20 bags	18.00	39	0	10	0
        ///2	Chang	1	1	24 - 12 oz bottles	19.00	17	40	25	0
        ///3	Aniseed Syrup	1	2	12 - 550 ml bottles	10.00	13	70	25	0
        ///4	Chef Anton&apos;s Cajun Seasoning	2	2	48 - 6 oz jars	22.00	53	0	0	0
        ///5	Chef Anton&apos;s Gumbo Mix	2	2	36 boxes	21.35	0	0	0	1
        ///6	Grandma&apos;s Boysenberry Spread	3	2	12 - 8 oz jars	25.00	120	0	25	0
        ///7	Uncle Bob&apos;s Organic Dried Pears	3	7	12 - 1 lb  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionId	RegionDescription
        ///1	Eastern                                           
        ///2	Western                                           
        ///3	Northern                                          
        ///4	Southern                                          .
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipperId	CompanyName	Phone
        ///1	Speedy Express	(503) 555-9831
        ///2	United Package	(503) 555-3199
        ///3	Federal Shipping	(503) 555-9931.
        /// </summary>
        public static string Shippers {
            get {
                return ResourceManager.GetString("Shippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierId	CompanyName	ContactName	ContactTitle	Address	City	Region	PostalCode	Country	Phone	Fax	HomePage
        ///1	Exotic Liquids	Charlotte Cooper	Purchasing Manager	49 Gilbert St.	London	NULL	EC1 4SD	UK	(171) 555-2222	NULL	NULL
        ///2	New Orleans Cajun Delights	Shelley Burke	Order Administrator	P.O. Box 78934	New Orleans	LA	70117	USA	(100) 555-4822	NULL	#CAJUN.HTM#
        ///3	Grandma Kelly&apos;s Homestead	Regina Murphy	Sales Representative	707 Oxford Rd.	Ann Arbor	MI	48104	USA	(313) 555-5735	(313) 555-3349	NULL
        ///4	Tokyo Traders [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TerritoryId	TerritoryDescription	RegionId
        ///01581	Westboro                                          	1
        ///01730	Bedford                                           	1
        ///01833	Georgetow                                         	1
        ///02116	Boston                                            	1
        ///02139	Cambridge                                         	1
        ///02184	Braintree                                         	1
        ///02903	Providence                                        	1
        ///03049	Hollis                                      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Territories {
            get {
                return ResourceManager.GetString("Territories", resourceCulture);
            }
        }
    }
}
